### ISSUE TITLE
Why remove 'cf files' does not work on Diego?

### ISSUE THREAD

**Issue by hpejcinovic-pivotal** [cloudfoundry/docs-dev-guide#132]
Hi,
In previous versions of this page, it used to state
Diego does not support the <code>cf files</code> command.

Could we please put this back.

https://github.com/cloudfoundry/docs-dev-guide/commit/977bdbfda99ebd4939a617f169c7226727eef2c6

**Comment by ljarzynski** [comment]
Thanks for the feedback @hpejcinovic-pivotal, I just made a commit that puts a note in: https://github.com/cloudfoundry/docs-dev-guide/commit/abee7a8aae098c4f2a112f11d9fcda1a6033d10d#diff-6d542044acbaecda56492549a92b3631R224.
