### ISSUE TITLE
CF_INSTANCE_GUID is not the same as an application's GUID 

### ISSUE THREAD

**Issue by glyn** [cloudfoundry/docs-dev-guide#142]
The [docs](https://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html#CF-INSTANCE-GUID) describe CF_INSTANCE_GUID as:

> The GUID of the application. [...]

However, applications (running on Diego) appear to have their GUID stored in VCAP_APPLICATION (in "application_id") and this value is not the same as CF_INSTANCE_GUID. So presumably the CF_INSTANCE_GUID is something other than the GUID of the application.

**Comment by ljarzynski** [comment]
@ematpl Are you able to help with this? Do you know what CF_INSTANCE_GUID is referring to?

**Comment by ematpl** [comment]
Yes, the content of that `CF_INSTANCE_GUID` environment variable is a v4 UUID unique to each particular instance of an app (or in general a Diego DesiredLRP). It is not the same as the GUID that CC assigns to a CF application.

Thanks,
Eric

**Comment by ljarzynski** [comment]
Thanks again @glyn and @ematpl. I just updated this in the doc to resolve this issue: https://github.com/cloudfoundry/docs-dev-guide/commit/77b3859943359128364c7074250b71f3293a14ce

**Comment by glyn** [comment]
Thanks @ljarzynski. BTW did you notice the inconsistent description of GUIDs as "GUID", "UUID", and "Unique ID". It would be good if these were all consistent, but I'll leave that to your judgement.

**Comment by ljarzynski** [comment]
@glyn, thanks for pointing that out. The documentation really should be consistent on this. I'll create a story to do that for this topic.
