### ISSUE TITLE
Clarify in domain management that CNAME record details

### ISSUE THREAD

**Issue by cdavisafc** [cloudfoundry/docs-dev-guide#17]
Each of the examples currently shows that the CNAME or ALIAS targets yourappname.cfapps.io, implying that the application should have also been mapped to this uri. In reality, during DNS resolution the yourappname part is ignored because of the wildcard entry so it would probably be clearer to say foo.cfapps.io with a footnote explaining this.

**Comment by elenasharma** [comment]
Our recent edits to this topic have covered this issue, so I'm closing it out.

Thanks!
