### ISSUE TITLE
Not documented how to disable ssh access globally

### ISSUE THREAD

**Issue by zrob** [cloudfoundry/docs-dev-guide#171]
This page `app-ssh-overview.html` mentions it is possible for the operator to disable it, but doesn't say how.

This page `deploy-apps/ssh-apps.html` mentions that an operator can disable access globally but doesn't say how.

The manifest property is `cc.allow_app_ssh_access`

**Comment by ljarzynski** [comment]
Hi @zrob ! Thanks for opening this issue. Seems like we can do a better job of helping folks find these steps, as they do exist in http://docs.cloudfoundry.org/running/config-ssh.html#disable-ssh. I wll go ahead and add links from the two pages you mentioned.

**Comment by ljarzynski** [comment]
See the following commits: 

https://github.com/cloudfoundry/docs-dev-guide/commit/0f33ab351b9c444294cabac8505376ed25085a81

https://github.com/cloudfoundry/docs-book-cloudfoundry/commit/dcc2da8a74fda44e64e78f7c0f7e5a6e8790b452
