### ISSUE TITLE
cf scale questions

### ISSUE THREAD

**Issue by johnyesberg** [cloudfoundry/docs-dev-guide#174]
Hi, thanks for your work on the documentation. I thought I'd offer some comments from a new user perspective. 

https://docs.cloudfoundry.org/devguide/deploy-apps/cf-scale.html

With -i, cf may remove some of my instances. Will it choose these at random? Or the least recently used? Does my app need to take account of the possibility that an instance may be removed while it is serving a request? I assume this is good practice, but wondering how hard the framework tries to insulate me from this situation.

With -m (and -k), I imagine these changes take effect while the app is running. Should I think of this command as changing the memory allocated to the VM? Can that happen in real time, or does the VM need to be paused? If the app uses a JVM with a command line (e.g. -Xmx) argument to set max memory, will cf scale -m restart the app instance?

**Comment by ljarzynski** [comment]
@johnyesberg Thanks for filing this issue. 

@dkoper Would appreciate your help on answering these questions if you are able.

**Comment by dkoper** [comment]
@ematpl or @zrob can confirm the details, but I'll take a first stab:
- `-i, cf may remove some of my instances` - I believe it stops and removes the instances with the highest index number (each app instance has an index number, as listed in `cf app your-app`).
- [This article](https://docs.cloudfoundry.org/devguide/deploy-apps/app-lifecycle.html#shutdown) explains how your app instance is stopped.
- `-m` and `-k` currently need an app restart to take effect. `cf scale` will prompt for confirmation unless `-f` is used.
- It is the memory made available to the app container, so is shared by the OS, JVM and anything else that may be running inside. Java Buildpack 3.1 and higher calculate how much memory can be assigned to the VM (like `-Xmx`) at container startup time. (In versions before that, it was calculated at staging time so required a restage for changes to take effect).
