### ISSUE TITLE
Using Application Health Checks - conflicting timeout information

### ISSUE THREAD

**Issue by johnyesberg** [cloudfoundry/docs-dev-guide#175]
Hi. On the [Using Application Health Checks page](https://docs.cloudfoundry.org/devguide/deploy-apps/healthchecks.html)  I see the http health check explanation includes:

> The configured endpoint must respond within **1 second** to be considered healthy.

But lower down, the Health Check Timeouts section says:

> In Cloud Foundry, the default timeout is **60 seconds** and the maximum configurable timeout is 180 seconds.

Either these are inconsistent, or things are more complex than I understand.

**Comment by ljarzynski** [comment]
@johnyesberg Thanks for filing this issue.

@ematpl Would appreciate your help in answering in explaining these seemingly disagreeing statements, if you are able.

**Comment by ematpl** [comment]
@ljarzynski, there are two different time-scales here. That 60-second interval is the default timeout for the app instance to become healthy. During that interval, and after the instance subsequently becomes healthy, the Diego cell will perform many health-check attempts, and each individual attempt has a timeout of 1 second.

**Comment by ljarzynski** [comment]
I see. Thanks @ematpl ! 

@johnyesberg Does this help?

**Comment by johnyesberg** [comment]
Hi @ematpl and @ljarzynski . Now I understand. Thanks for your time and work on CF.
