### ISSUE TITLE
space_name missing from VCAP_APPLICATION

### ISSUE THREAD

**Issue by Adam10003** [cloudfoundry/docs-dev-guide#178]
Every example of a VCAP_APPLICATION environment variable I have found has the space_name attribute set (including examples in the same doc), however the list of VCAP_APPLICATION attributes in deploy-apps/environment-variable.html.md.erb omits it.

Is this intentional?

Thanks,
- Adam

**Comment by animatedmax** [comment]
Resolved with commit: 43fb7b983b35fdf7a1f58c87bf901750ff7b8314
