### ISSUE TITLE
Query on Documentation

### ISSUE THREAD

**Issue by vipinvkmenon** [cloudfoundry/docs-dev-guide#179]
The documentation states: Authorization Token Grace Period is Minimum 20 Minutes.

Is it supposed to be "Minimum" 20 minutes or "Maximum" 20 Minutes? If the minimum time for the Authorization is 20 Minutes. what is the maximum time?
Thanks

**Comment by cf-pub-tools** [comment]
Hi @vipinvkmenon 

This documentation repository is maintained by technical writers, not developers or support engineering. 

If you have questions about the open source Cloud Foundry project, we recommend that you contact the cf-dev@lists.cloudfoundry.org mailing list.

For questions about Pivotal Cloud Foundry, please contact Pivotal support: https://support.pivotal.io

Thank you.
