### ISSUE TITLE
document how the .profile.d directory is used for pushed applications

### ISSUE THREAD

**Issue by adamstegman** [cloudfoundry/docs-dev-guide#18]
From [cloudfoundry/cf-docs#213](https://github.com/cloudfoundry/cf-docs/issues/213):

> I'm not sure where in the doc set to put it, but we have an entirely undocumented feature that seems to be essentially the same as what is described here: https://devcenter.heroku.com/articles/profiled. I've tried following this guidance from the heroku docs and it looks like it works fine. We need to include this as well.

/cc @cdavisafc

**Comment by animatedmax** [comment]
Completed with https://www.pivotaltracker.com/story/show/70728708

Thanks, adamstegman !
