### ISSUE TITLE
Update Splunk integration docs to use firehose/nozzle approach

### ISSUE THREAD

**Issue by halr9000** [cloudfoundry/docs-dev-guide#191]
Docs currently for the Splunk integration ([docs-dev-guide/services/integrate-splunk.html.md.erb](https://github.com/cloudfoundry/docs-dev-guide/blob/master/services/integrate-splunk.html.md.erb)) specify an outdated approach of sending app data out as syslog. More recently (Jan 2017), @cholick wrote a [guest blog post on Splunk.com](https://www.splunk.com/blog/2017/01/19/getting-cloud-native-with-splunk-and-cloud-foundry.html) which shows how to use [splunk-firehose-nozzle](https://github.com/cloudfoundry-community/splunk-firehose-nozzle) to get the job done.

Can this docs page be refactored to use this new technique? I see no compelling reason that the historical syslog technique should remain.

**Comment by halr9000** [comment]
@haydonryan can you comment? You guys are using the nozzle IIRC with that cu in Atlanta, correct?

**Comment by cholick** [comment]
It's definitely worth highlighting the nozzle, but an application developer might not have the `doppler.firehose` uaa scope. So I do think it's good to mention syslog as a fallback for things like multi-tenant Cloud Foundry installations.

**Comment by halr9000** [comment]
@rarsan any luck with finding an owner to update these docs?

**Comment by rarsan** [comment]
@chenziliang
