### ISSUE TITLE
Health Check Timeout is 600s max and not 180

### ISSUE THREAD

**Issue by agregory999** [cloudfoundry/docs-dev-guide#200]
Can we double check - the docs say 180, and my customer wanted longer.  The CF Push allows 600 as a timeout before an error occurs.

**Comment by dkoper** [comment]
What do you mean with `CF Push allows 600`?

```
D:\Users\koperd\Downloads\bin>cf p hct -p t\n -t 181
Creating app hct in org dies-test / space dev as admin...
FAILED
Server error, status code: 400, error code: 100001, message: The app is invalid: health_check_timeout Maximum exceeded: max 180s

D:\Users\koperd\Downloads\bin>cf p hct -p t\n -t 180
Creating app hct in org dies-test / space dev as admin...
OK
```

**Comment by agregory999** [comment]
Odd - I am running the latest I thought and I can put in up to 600. My customer wanted 300 and tried it too. He confirmed the behavior works for 5 min. 

Andrew

**Comment by dkoper** [comment]
The value seems server-side configurable. Which is probably why we avoided mentioning the value in cf CLI help output.
https://github.com/cloudfoundry/cloud_controller_ng/blob/674202f2dd6135f4acf91ed9b08416a5a5d8bcec/bosh/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb#L242

@animatedmax What's your approach with such cases for the docs? Maybe you'd like to add a note that the value is server-side configurable so could be different than 180?

**Comment by animatedmax** [comment]
We can replace "the maximum configurable timeout is 180 seconds" with "the default maximum configurable timeout is 180 seconds" and add that "Your Cloud Foundry operator can set other values for these defaults."

**Comment by pspinrad** [comment]
Or how about:
> The `timeout` attribute defaults to 60, but you can set it to any value up to the Cloud Controller's `maximum_health_check_timeout` property. `maximum_health_check_timeout` defaults to 180, but your Cloud Foundry operator can set to any value.

Then consider deleting that first note-- not relevant if this is for developers not operators.
http://docs.pivotal.io/pivotalcf/1-12/devguide/deploy-apps/manifest.html#timeout

**Comment by dkoper** [comment]
That sounds good to me, including deleting the note!
