### ISSUE TITLE
How to use Volume Services with LDAP

### ISSUE THREAD

**Issue by apel89** [cloudfoundry/docs-dev-guide#215]
Would like instructions for how to securely use Volume Services with LDAP as of CF v1.12.

using-vol-services.html.md.erb

Thanks!

**Comment by ljarzynski** [comment]
@apel89 Thanks for filing this issue! 
We could definitely use an explanation of how to enable LDAP support as a CF operator. 
If you enable LDAP support, developers must provide credentials for any user they wish to bind as.
I'll work with the engineering team to get the "How to enable" information added to this page: http://docs.cloudfoundry.org/running/deploy-vol-services.html. 
In the meantime, you may find the following doc useful for your purposes: https://github.com/cloudfoundry/nfs-volume-release/blob/master/USING_LDAP.md. Located in the CF NFS Volume release repo, it discusses how to integrate an LDAP Server with nfs-volume-release.
cc @julian-hj

**Comment by ljarzynski** [comment]
@apel89 I realized that given your reference to CF v1.12, you may have been referring to how to do use LDAP in a PCF environment. In that case, the Operator would have to enter LDAP details in the Application Containers config pane of Elastic Runtime. For more info, see: https://docs.pivotal.io/pivotalcf/1-12/customizing/gcp-er-config.html#application-containers-config. 

Does this and the previous response answer your question? Or is there anything else I can clarify/get answers on?
