### ISSUE TITLE
How to setup SSL certificates for a private domain as org owner?

### ISSUE THREAD

**Issue by bufferoverflow** [cloudfoundry/docs-dev-guide#225]
I'm able to see how to setup a private domain for a space, but I do not know how to add the certificates or at least I was not able to find them here: https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html

**Comment by cshollingsworth** [comment]
Hi, @bufferoverflow -- you should now be able to find the information you're looking for [here](https://docs-cloudfoundry-staging.cfapps.io/devguide/deploy-apps/routes-domains.html#domains-dns) in the topic.

**Comment by animatedmax** [comment]
https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#domains-dns
