### ISSUE TITLE
Line does not interpolate tcp _app_domain properly

### ISSUE THREAD

**Issue by alamages** [cloudfoundry/docs-dev-guide#230]
https://github.com/cloudfoundry/docs-dev-guide/blob/880131089e0c12a7e0b2b052c875f2c0ae37590e/deploy-apps/routes-domains.html.md.erb#L408

If you check this line in the docs it does not display properly.

**Comment by animatedmax** [comment]
Hi @alamages Thank you for your feedback. The line should now display properly on all our documentation sets.
