### ISSUE TITLE
Cats and Dogs example container to container networking missing

### ISSUE THREAD

**Issue by jordo1138** [cloudfoundry/docs-dev-guide#237]
It was removed with comment here https://github.com/cloudfoundry/cf-networking-release/commit/ef02f4f553c448b5aaf9cf7587a2a4fce3554816

but the new link to the new repo is not found in the doc's page under Administering Container to Container Networking 

12. (Optional) Try the Cats and Dogs example in the Container-to-Container Networking Release repository. In this tutorial, you deploy two apps and create a Container-to-Container Networking policy that allows them to communicate directly with each other.
https://github.com/cloudfoundry-incubator/cf-networking-release/tree/develop/src/example-apps/cats-and-dogs  now a 404

**Comment by pspinrad** [comment]
@jordo1138 thanks-- what's the new link for the Cats and Dogs example?

**Comment by jordo1138** [comment]
Kinda hidden https://github.com/cloudfoundry/cf-networking-examples

**Comment by animatedmax** [comment]
Hi @jordo1138 This link should now be fixed. Thanks!
