### ISSUE TITLE
mysql not found

### ISSUE THREAD

**Issue by talk2amareswaran** [cloudfoundry/docs-dev-guide#239]
After successful ssh if I execute the mysql command - then I am getting mysql not found error.

**Comment by seviet** [comment]
hey @talk2amareswaran - can you be specific about which page of documentation you are trying to follow so we can determine whether this is a doc issue? also, for immediate & general troubleshooting assistance I recommend reaching out on the https://cloudfoundry.slack.com/ - either in #general or #cf-users

**Comment by seviet** [comment]
closing this out. if there's a specific doc issue to be fixed, please feel free to re-open or create a new issue.
