### ISSUE TITLE
scalablesyslog.adapter.metrics_to_syslog_enabled

### ISSUE THREAD

**Issue by agregory999** [cloudfoundry/docs-dev-guide#243]
It isn't obvious or documented what to do here:

"To include container metrics in your syslog drain, an operator must first set the scalablesyslog.adapter.metrics_to_syslog_enabled to true"

Can you say exactly how to do this, where from? Is this an Operator or User operation?

**Comment by mjgutermuth** [comment]
Hi there, apologies for the very late response! We did make these changes and didn't get the chance to follow up here. Thanks for bringing this up!
