### ISSUE TITLE
Suggest using `cf run-tasks` for DB migrations

### ISSUE THREAD

**Issue by troytop** [cloudfoundry/docs-dev-guide#247]
The [Migrating a Database in Cloud Foundry](https://docs.cloudfoundry.org/devguide/services/migrate-db.html) page currently lists a few methods for migrating app databases. These procedures seem to predate `cf tasks` (though the tasks method is mentioned as of 0474c78ee3562eaa152b91cc4050ec319499459b).

If others agree, I think `cf run-task ...` should be the preferred method of running database migrations for all three scenarios listed (once, occasionally, frequently).

**Comment by mjgutermuth** [comment]
Hi there, apologies for the very late response! We did address this issue and did not get the chance to follow up here. Thanks for pointing this out!
