### ISSUE TITLE
`maximum_health_check_timeout` is 600 by default and is not configurable

### ISSUE THREAD

**Issue by wgu** [cloudfoundry/docs-dev-guide#253]
https://docs.pivotal.io/pivotalcf/1-12/devguide/deploy-apps/manifest.html#timeout

This section has the following statement which could be wrong:

`maximum_health_check_timeout` defaults to 180, but your Cloud Foundry operator can set to any value.

Can we confirm this and update?

**Comment by mlimonczenko** [comment]
Hello @wgu. I investigated this issue and it turns out this phrase is accurate. The property `maximum_health_check_timeout` does default to 180 (in seconds) and the value is configurable.

**Comment by wgu** [comment]
@mlimonczenko which version did you check? In my lab install for 1.12.1 the value is 600 and I don't see a place in Ops Manager that an operator can configure that. Is it changed in a later version?

**Comment by mlimonczenko** [comment]
Alright, @wgu. I looked into it again, and you're right.

There is a discrepancy between open source Cloud Foundry and the commercial Pivotal Cloud Foundry. In the PAS tile, it's 600 and nonconfigurable. I can update the Pivotal docs to reflect this.

Thank you so much for bringing this to our attention!
