### ISSUE TITLE
Please fix anchor link for Variable Substitution section

### ISSUE THREAD

**Issue by abbyachau** [cloudfoundry/docs-dev-guide#266]
Hi there,

When I click on Variable Substitution on the Deploying with Application Manifests page, the anchor is:

https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#multi-manifests

Please could you fix the anchor to something like #variable-substitution

Thanks,

Abby

**Comment by animatedmax** [comment]
Hi @abbyachau We've made this change. Thanks!

**Comment by abbyachau** [comment]
Thank you @animatedmax!
