### ISSUE TITLE
Network Policy Wife off after app restage.

### ISSUE THREAD

**Issue by kumarganesh2814** [cloudfoundry/docs-dev-guide#267]
Hi Team,

On restaging of application which had existing network policies, post application start up the policies are being wiped off. can you please assist or are we missing any step here.

Or How to keep Network policies forever untill we do force delete.

Best Regards
Ganesh Kumar

**Comment by tylerschultz** [comment]
Hi Ganesh,

Would you please open an issue against http://github.com/cloudfoundry/cf-networking-release? 

Are you able to recreate this issue reliably, or is it only sometimes? 

We've heard of this happening, but we've never been able to recreate it. Please gather the policy-server and policy-server-internal logs off of the api vms in your deployment. Hopefully we can work together to find out what is happening.

--Tyler (CF Networking Eng)

**Comment by tylerschultz** [comment]
This sounds potentially related to https://github.com/cloudfoundry/cf-networking-release/issues/42

**Comment by pspinrad** [comment]
Hi Ganesh-- yes, please open this issue against http://github.com/cloudfoundry/cf-networking-release -- thanks!  Closing this story here.
