### ISSUE TITLE
Documentation for deprecated features

### ISSUE THREAD

**Issue by kzbt** [cloudfoundry/docs-dev-guide#281]
For reasons that are beyond me, our systems use an older version of cf cli. Recently I found out that we can't use variable substitution yet since it is in the newer version. An alternative seemed to be inheritance. However, [I couldn't find any info regarding how to use it](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#inheritance-deprecated). Would it be possible to preserve the documentation of deprecated features at least untill they are completely removed?

**Comment by pspinrad** [comment]
@kjsebastian well, there's this https://web.archive.org/web/20160319120815/https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html -- courtesy Internet Archive.  But I agree we shouldn't unpublish docs for features that are deprecated but still work @abbyachau @zrob

**Comment by mlimonczenko** [comment]
Hello @kzbt,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
