### ISSUE TITLE
Issue while creating the SSH Tunnel

### ISSUE THREAD

**Issue by arindamroy321** [cloudfoundry/docs-dev-guide#283]
> cf ssh -L 63306:us-cdbr-iron-east-01.cleardb.net:3306 eshopping
FAILED
Error opening SSH connection: dial tcp 52.4.51.132:2222: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Please let us know the solution to this problem.

**Comment by seviet** [comment]
hi @arindamroy321 -- it looks like you're trying to troubleshoot a connection issue in CF. i recommend that you reach out for help in the https://cloudfoundry.slack.com -- perhaps either the #general or #cf-users channel. If you discover something that you believe requires a documentation update, please feel free to open up a new issue!
