### ISSUE TITLE
cf add-network-policy : What happens if app restarts / BG Deployment happens

### ISSUE THREAD

**Issue by marunk20** [cloudfoundry/docs-dev-guide#289]
Also please clarify in the page on what exactly does this `cf add-network-policy` command executes behind, does it connects `GUID` of both the Apps ?

what happens if the destination app gets crashed and a new container is placed by Dieoo ? still C2C works ?

what if a new deployment of destination app happens, does C2C still works ? Please add these information too. Thanks

Regards
Arun

**Comment by ljarzynski** [comment]
Hi @marunk20 ! Thanks for creating this issue. 

I've spoken with the CF Networking team. What I learned:
An app always retains the same GUID if it crashes, gets placed into a new container, or gets redeployed, and C2C still works. C2C is always aware of the GUIDs of the apps. 

Pushing a brand new app would require a new c2c policy, but not udpates to existing apps. 

Does this help?
