### ISSUE TITLE
CF ignores Docker EXPOSE port

### ISSUE THREAD

**Issue by teespoon** [cloudfoundry/docs-dev-guide#301]
https://docs.pivotal.io/pivotalcf/2-2/devguide/deploy-apps/push-docker.html#port_config

...says...

> If you specify the EXPOSE directive, then the corresponding app pushed to Cloud Foundry listens on that exposed port. 

This doesn't seem to be the case.  Is there a way to truly expose a non-standard port?  Is there a better way to test?

### Simple Example
For simplicity, use a public docker hub image with an EXPOSE directive.  For example,
- https://hub.docker.com/_/redis/  [includes EXPOSE 6379]*
_* redis should not really be run this way in CF... this approach is just for docker testing.  Other dockerfiles exposing other non-standard CF ports should generate similar results.  Just find a simple docker image to test with._

To test...

1. Push a docker image that has an EXPOSE directive with a specialized port.
```
> cf push myredis --docker-image redis
```

2. Connect over ssh and ensure that redis is running.  Exit ssh.
```
> cf ssh myredis
root@89bda883-c461-46e8-5a5a-8fe0:~# /usr/local/bin/redis-cli ping
PONG
root@89bda883-c461-46e8-5a5a-8fe0:~# exit
exit
```

3. Try to connect externally via the "exposed" port:
```
> redis-cli -h myredis.cfapps.io -p 6379 ping
```   
**no PONG = no joy**

### Cross-Checks
- app is running and URL is correct: `> cf app myredis` 
- telnet to port 80 to prove the url is reachable: `> telnet myredis.cfapps.io 80`
- telnet to port 6379 to prove the port is not operational: `> telnet myredis.cfapps.io 6379`
- ensure network allows traffic on the port (6379):  http://portquiz.net:6379
- run the image in docker locally and ping it with redis-cli to prove docker image is good
- use both PWS and cf dev to ensure that one or the other is not doing something unusual to interfere with non-standard port traffic
- try other docker images that expose other ports

**Comment by emalm** [comment]
Hi, @teespoon, in this case you need to create a TCP route and then map that route to your `redis` app instance in order to send traffic to it over the public internet. By default, CF provides HTTP routes to apps, but that doesn't work correctly for Redis because its protocol is not HTTP-based. The CF docs have instructions for creating the route at https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#create-route-with-port.

Depending on how your platform operator has configured CF, you may need to request that the ability to provision TCP routes be added to your organization quota, and the publicly routable port for the TCP route will almost certainly be different from the standard 6379 Redis port.

Best,
Eric, CF Diego PM

**Comment by teespoon** [comment]
Thanks, @emalm for the quick response and detailed advice.  But I think I'm missing a piece?

The simplistic example below attempts to follow the instructions using **CF DEV** as admin to allow provisioning of TCP router-groups, domains, routes, and ports to demo how a non-standard port from a docker image could be exposed by CF.  (Obviously we would not use Redis this way in a real environment... this is just to demo an EXPOSE directive being respected by CF.)

1. Create an app from docker that exposes a custom port. (ex: EXPOSE 6379).
```
PS C:\path> cf push myredis --docker-image redis
```
2. Discover the default TCP router-group GUID and modify it to include the desired port range...
```
PS C:\path> cf curl /routing/v1/router_groups
PS C:\path> $token = cf oauth-token
PS C:\path> $json=@"
>> {\"reservable_ports\": \"6370-6390\"}
>> "@
PS C:\path> cf curl /routing/v1/router_groups/d6962e2e-7099-4f79-79d8-aef0612cde04 -X PUT -d $json -H "Authorization: $token"
```
3. Create TCP domain and map a TCP route...
```
PS C:\path> cf create-shared-domain tcp.dev.cfdev.sh --router-group default-tcp
PS C:\path> cf create-route cfdev-space tcp.dev.cfdev.sh --port 6379
PS C:\path> cf map-route myredis tcp.dev.cfdev.sh --port 6379
```
4. Verify setup...
```
PS C:\path> cf routes
Getting routes for org cfdev-org / space cfdev-space as admin ...

space         host      domain             port   path   type   apps      service
cfdev-space   myredis   dev.cfdev.sh                            myredis
cfdev-space             tcp.dev.cfdev.sh   6379          tcp    myredis
```
**The domain maps to CF, but CF ignores traffic on this port.**  (This still fails.)
```
PS C:\path> redis-cli -h tcp.dev.cfdev.sh ping
```

How to we tell CF we want non-standard port traffic (like 6379) to not be ignored?  Thanks again!

**Comment by emalm** [comment]
Hi, @teespoon, I'm not certain how CF-Dev is setup, but I can get this to work correctly on the CF [deployed](https://github.com/cloudfoundry/cf-deployment/blob/master/deployment-guide.md) to my local [VirtualBox-based BOSH-Lite](https://bosh.io/docs/bosh-lite/), using the TCP router IP address (`10.244.0.136`) as a new shared TCP domain:

```
$ cf curl /routing/v1/router_groups
[
   {
      "guid": "b3dd0960-86df-46ee-666d-f93a83d9d3ac",
      "name": "default-tcp",
      "type": "tcp",
      "reservable_ports": "1024-1123"
   }
]

$ cf curl /routing/v1/router_groups/b3dd0960-86df-46ee-666d-f93a83d9d3ac -X PUT -d '{"reservable_ports":"1024-6399"}'
{
   "guid": "b3dd0960-86df-46ee-666d-f93a83d9d3ac",
   "name": "default-tcp",
   "type": "tcp",
   "reservable_ports": "1024-6399"
}

$ cf create-shared-domain 10.244.0.136 --router-group default-tcp
$ cf push redis -o redis --no-route
$ cf map-route redis 10.244.0.136 --port 6379
$ redis-cli -h 10.244.0.136 ping
PONG
```

I'd suggest [filing an issue on the cfdev repo](https://github.com/cloudfoundry-incubator/cfdev/issues) if you're having problems doing the analogous setup there.

In general, this isn't merely an issue of telling CF not to ignore certain ports: the 6379 port that the redis process listens on in its CF container is local only to that container, and is NATed to a high-numbered port on the CF container host (the Diego cell). The TCP router then discovers that port through the routing control plane and proxies TCP traffic to it. The TCP route setup commands above are designed to get traffic routed correctly only up to that TCP router, which handles the traffic from there to the container host and then into the container to the redis process.

**Comment by teespoon** [comment]
Looks good, but this doesn't work for CF Dev 0.0.11 no matter how closely I follow the example.  (The CF setup works fine, but I can't use redis-cli or telnet to get access to the port at the end.)

**Things to check:**

1. Maybe I'm using the wrong **_IP address._**  What is the proper way to discover the TCP Router IP Address?  I'm just using `nslookup foo.dev.cfdev.sh` and/or `ping nslookup foo.dev.cfdev.sh`.

2.  I can try older _**versions**_ of CF Dev to see if the functionality works in one, but not the other.

3. The method shown in your example does not seem to follow the documentation because it uses an IP address instead of a **_domain name_**.  Are you purposely avoiding a domain name or is the documentation inexact in some way?  I don't see that it would be functionally different, but it is different. 
 Some examples:

https://docs.cloudfoundry.org/adminguide/enabling-tcp-routing.html#pre-deploy
> Choose a domain name from which your developers will create TCP routes for their applications. For example, create a domain which is similar to your app domain but prefixed by the TCP subdomain: tcp.APPS-DOMAIN.com

https://docs.cloudfoundry.org/adminguide/enabling-tcp-routing.html#configure-domain

> Run cf create-shared-domain to create a shared domain and associate it with the router group.
> 
> $ cf create-shared-domain tcp.APPS-DOMAIN.com --router-group default-tcp

Thanks!

**Comment by emalm** [comment]
Hey, @teespoon, I'm not familiar with CF Dev myself, so if the TCP Router address isn't apparent from its docs or setup procedure I'd still suggest raising an issue.

Yeah, for this setup it doesn't matter that the name of the TCP domain is actually an IP address. DNS resolution to an IP address will happen client-side, and with bare TCP there's no metadata indicating the domain to which the client connected (unlike with HTTP, where it's included in the request's `Host` header). IP addresses happen to match the allowed pattern of a DNS domain name, so CC allows them to be registered. I could have used something like `10.144.0.136.xip.io` as the domain name (since the xip.io service resolves any `A.B.C.D.xip.io` DNS name to the IP `A.B.C.D`) if it were required to use a valid DNS domain name, but that one would require communication with that name server on the public internet to resolve. You could use a similar xip.io domain yourself once you determine the correct IP to which to route traffic to the CF Dev TCP router.

**Comment by teespoon** [comment]
@emalm, thanks again for your time and explanations.  I think we have done all we can here.

I will test our basic configuration above with several different versions of CF Dev and then follow up with the CF Dev crew on a different issue number and link back to this one (if I still can't get access to a non-standard port).
