### ISSUE TITLE
The application manifest documentation is missing the "instances" option

### ISSUE THREAD

**Issue by lcrespom** [cloudfoundry/docs-dev-guide#303]
This page: https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html
Which corresponds to this file: https://github.com/cloudfoundry/docs-dev-guide/blob/master/deploy-apps/manifest.html.md.erb

Is missing documentation about the `instances` option in the "Optional Attributes" section.

**Comment by jncd** [comment]
@lcrespom This issue was closed by this commit: https://github.com/cloudfoundry/docs-dev-guide/pull/401 Happy to be closing it at last.
