### ISSUE TITLE
App-Lifecycle:Evacuate' vs 'Run Multiple Instances to Increase Availability'

### ISSUE THREAD

**Issue by eruvanos** [cloudfoundry/docs-dev-guide#312]
In the section about evacuation the text uses the example of updating Diego cells would trigger an evacuation, which would start new app instances before shutting down the old ones.
-> https://docs.cloudfoundry.org/devguide/deploy-apps/app-lifecycle.html#evacuation

But the page about 'Prepare to Deploy' describes the opposite.
-> https://docs.cloudfoundry.org/devguide/deploy-apps/prepare-to-deploy.html

**Comment by pspinrad** [comment]
@eruvanos Thanks, yes-- first link ^ says:

> CF recreates the app instances on another VM, waits until they are healthy, and then shuts down the old instances.

...but the second says:

> To avoid the risk of an application being unavailable during a Cloud Foundry upgrade processes, you should run more than one instance of the application.

@emalm is there something incorrect or missing behind this apparent contradiction?  Thanks!

**Comment by emalm** [comment]
Hi, @eruvanos and @pspinrad,

The description in https://docs.cloudfoundry.org/devguide/deploy-apps/app-lifecycle.html#evacuation of the Diego cells' behavior during evacuation is correct. One aspect of that behavior we may want to call out is that the replacement process is not guaranteed: in particular, if the replacement instance does not become healthy within the cell's evacuation timeout (defaulting to 10 minutes), the cell rep still shuts down and takes the existing app instance with it. As a result, app developers with a very low tolerance for unexpected downtime may prefer to run several instances of their app to forestall this possibility. Of course, the other risk associated to running only a single app instance is that an unexpected fault in the CF system components or underlying infrastructure (container-host VM, IaaS availability zone) may cause that lone app instance to disappear or to become unroutable and to take a minute or two to recover. I think it would make sense to revise https://docs.cloudfoundry.org/devguide/deploy-apps/prepare-to-deploy.html to recommend running several app instances for those reasons, but to point out that apps with more end-user tolerance for brief periods of unavailability may find it acceptable to run only a single app instance.

Thanks,
Eric
