### ISSUE TITLE
Exist a parameter to set disk space in manifest.yml?

### ISSUE THREAD

**Issue by mmc2004jp** [cloudfoundry/docs-dev-guide#32]
'docs-dev-guide/deploy-apps/large-app-deploy.html.md.erb' says:
Use either the -k flag with cf push or set a disk space allocation value in your manifest.yml file.

However, I can't find any parameter to set a disk space allocation vale in manifest.yml file.
ref. http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html
So, I guess the sentence should be changed like below:
Use the -k flag with cf push

**Comment by jennjblack** [comment]
Hi mmc2004jp,

Use the `disk_quota` key to set a disk space allocation value in a manifest file.
For example: disk_quota: 512M

We'll update the topic with this information. Thanks for submitting this issue!
