### ISSUE TITLE
The Java buildpack does not support pre-runtime hooks.

### ISSUE THREAD

**Issue by ywei2017** [cloudfoundry/docs-dev-guide#325]
I found this statement is contrary to what we have observed in our testing. In our testing, the pre-runtime hook works fine for the Java builpack. Is the doc out of date, or I stumbled in some unsupported feature?

**Comment by kdolor-pivotal** [comment]
@ywei2017 Thanks for your inquiry! The Java buildpack does not support pre-runtime hooks.
