### ISSUE TITLE
User-provide services and route-services cannot be shared

### ISSUE THREAD

**Issue by rm511130** [cloudfoundry/docs-dev-guide#329]
The text at https://github.com/cloudfoundry/docs-dev-guide/blob/master/services/sharing-instances.html.md.erb says it between the lines, but would it be possible to include in the documentation an explicit phrase or two that states: "User-provide services and route-services cannot be shared using the `cf share-service` command.

**Comment by mlimonczenko** [comment]
Hello @rm511130,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
