### ISSUE TITLE
Rolling Deployment links need to be fixed

### ISSUE THREAD

**Issue by xKaiser** [cloudfoundry/docs-dev-guide#335]
In the commit 3d7681a8fd4552a2ab33f2d79cd1d2d93f86318b by @ljarzynski, the document for Zero Downtime Deployments was moved and title changed to Rolling Deployments.

The document at https://docs.pivotal.io/pivotalcf/2-4/installing/highlights.html#zero-downtime still links to 

https://docs.pivotal.io/pivotalcf/2-4/devguide/deploy-apps/zero-downtime.html

instead of

https://docs.pivotal.io/pivotalcf/2-4/devguide/deploy-apps/rolling-deploy.html

**Comment by mlimonczenko** [comment]
Hello @xKaiser,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
