### ISSUE TITLE
'subdomain' attribute used in manifest examples

### ISSUE THREAD

**Issue by mmc2004jp** [cloudfoundry/docs-dev-guide#34]
In deploy-apps/manifest.html.md.erb file, there are manifest examples which use 'subdomain' attribute.
I'm not sure if 'subdomain' is valid. They should be 'host' instead of 'subdomain:'?

https://github.com/cloudfoundry/docs-dev-guide/blob/master/deploy-apps/manifest.html.md.erb#L430
  subdomain: tick09875

https://github.com/cloudfoundry/docs-dev-guide/blob/master/deploy-apps/manifest.html.md.erb#L478
  subdomain: 321flurry

**Comment by MichaelTrestman** [comment]
This appears to already have been fixed.
instructions say to use the host attribute to specify subdomains:
https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#host
