### ISSUE TITLE
Link to multi-app manifests moved

### ISSUE THREAD

**Issue by abbyachau** [cloudfoundry/docs-dev-guide#354]
Hey folks, 

**WHERE:** On this page: https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#no-route

**LOCATED:** Which is located here: docs-dev-guide/deploy-apps/manifest-attributes.html.md.erb

**ISSUE:** 
This sentence here points to an anchor which no longer exists. 

```
For more information, see Describing Multiple Apps with One Manifest below.
```

**FIX:** It looks like the content has been moved to https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#multi-apps. 

I'm also curious as to why the text went that explains that some flags do not work with multi-app manifests. 

Thanks a bunch!

**Comment by abbyachau** [comment]
Only two flags work with multi-app manifests: `-f` and `--no-start`.

**Comment by ljarzynski** [comment]
Made the following commit to correct the link and update the guidance around flags: https://github.com/cloudfoundry/docs-dev-guide/commit/89e0bdd4a2a7763735495ed79da9232631970c1f. 

It mentioned 
"do not use any flags except for -f", but I changed to 
"You cannot use any flags except for -f and --no-start"
