### ISSUE TITLE
defining more than one worker process in profile

### ISSUE THREAD

**Issue by Mazata** [cloudfoundry/docs-dev-guide#357]
Hello,
I am attempting to push a Python app with a web process and several worker processes performing different tasks.
I thought of simply adding a line to the Procfile as such:
`web: python main_web.py
worker: python main_worker1.py
worker: python main_worker2.py`
Sadly, when pushing the app (not matter if cf push of cf v3-push), only the web process and the bottom worker process are picked up. Is there a way to have several worker processes running? Should I specify something in my manifest.yml maybe?
Thanks

**Comment by mlimonczenko** [comment]
Hello, @Mazata. Unfortunately, we do not help with technical support. We are here to support you if you want to make revisions to the documentation. Apologies for having to close this issue.
