### ISSUE TITLE
No information about default path mentioned in docs-dev-guide

### ISSUE THREAD

**Issue by amiteshhh** [cloudfoundry/docs-dev-guide#367]
When we run `cf push` where *manifest.yml* is not containing **path** attribute, current folder will gets uploaded as mentioned here https://docs.cloudfoundry.org/cf-cli/getting-started.html#find-app.

Kindly update dev-guide with this information.
```yml
---
applications:
- name: MY-APP
```

**Comment by pspinrad** [comment]
Hi @amiteshhh -- would the note below convey that the running `cf push` without including `-f PATH` uses the _manifest.yml_ file in the current folder?

> **Note**: By default, the `cf push` command uses the `manifest.yml` file in your the app directory.  To specify a different location for the manifest, pass its local path to the `-f` flag when you run `cf push`.

**Comment by amiteshhh** [comment]
Yes @pspinrad thats what I meant.

**Comment by pspinrad** [comment]
@amiteshhh thanks-- will change it..
