### ISSUE TITLE
how to achieve the same using mtad.yaml

### ISSUE THREAD

**Issue by lucatoldo** [cloudfoundry/docs-dev-guide#371]
The documentation is very good, however I am missing an example on how to create a route between a port and a host.

For example, an application at hostname "myserver" is serving at port 8080 and at port 7070.
We need to address them using different hostnames, e.g.

"https://servera.cfapps.com:80/" should be binding to "https://myserver.cfapps.com:8080/"
"https://serverb.cfapps.com:80/" should be binding to "https://myserver.cfapps.com:7070/"

**Comment by mlimonczenko** [comment]
Hello @lucatoldo,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
