### ISSUE TITLE
Kindly Update documentation to remove the non-existent v3-app from step

### ISSUE THREAD

**Issue by vipinvkmenon** [cloudfoundry/docs-dev-guide#372]
As per the reference of [v3 commands](https://docs.cloudfoundry.org/devguide/v3-commands.html), it can be understood that the command `v3-app` does not exist.

The step: [`$ cf v3-app myapp`](https://github.com/cloudfoundry/docs-dev-guide/blob/edee1d63a423ef5f94f67359282163a42dc95212/multiple-processes.html.md.erb#L79)  will error to:
> 'v3-app' is not a registered command. See 'cf help -a'

From the [Issue raised here](https://github.com/cloudfoundry/cli/issues/1776#issuecomment-527970634), I understand that the documentation needs to be updated to
`$ cf app myapp`
Kindly update the same

**Comment by mjgutermuth** [comment]
Thanks for bringing this up! I'm closing this out since your PR addressed the issue.
