### ISSUE TITLE
Where to find more information about the router log

### ISSUE THREAD

**Issue by dellagustin-sap** [cloudfoundry/docs-dev-guide#374]
This page https://docs.cloudfoundry.org/devguide/deploy-apps/streaming-logs.html#rtr mentions the logs emitted by the router (RTR).

I am looking for more information on how the log, as in the example below, is formed, so that it can be parsed by a logging service.

Can someone please point me to the information and also link it in the dev guide docs?

**Comment by mlimonczenko** [comment]
Hello @dellagustin-sap,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
