### ISSUE TITLE
cli manifest ref doc is lacking sidecar 

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/docs-dev-guide#375]
https://docs.cloudfoundry.org/devguide/sidecars.html#tutorial mentions 

> Open and review the manifest.yml file. Under sidecars, the sidecar is specified with a name, process type, and start command.

However https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html does not mention the sidecar field

/CC @ljarzynski

**Comment by mjgutermuth** [comment]
@gberche thanks for pointing this out! We have added a section about sidecars to this topic: https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#sidecars
