### ISSUE TITLE
Documentation is incorrect for AWS ECR images

### ISSUE THREAD

**Issue by tminussi** [cloudfoundry/docs-dev-guide#379]
According to the [docs], issuing a `cf push` when providing both `AWS-SECRET-ACCESS-KEY` and `AWS-ACCESS-KEY-ID` should be enough to authenticate against `AWS ECR` and push images to CF successfully, but this is not the case.

Running the command specified in the documentation results in:

> Failed getting docker image manifest by tag: denied: Your Authorization Token is invalid.

`cf push` expects both the `user` and `password` returned by the `aws ecr get-login --no-include-email` command instead. 

[docs]: https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html#registry

**Comment by mjgutermuth** [comment]
Hi @tminussi, thank you for pointing this out and submitting a PR! We have merged your changes and you should see the updates reflected in the docs soon.

**Comment by tminussi** [comment]
Thanks, @mjgutermuth!

**Comment by sunjayBhatia** [comment]
@mjgutermuth @tminussi updated comment with links ^

**Comment by pspinrad** [comment]
@tminussi @sunjayBhatia to follow up-- I added this note to the CFAR docs https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html#ecr

**Note:** This feature is only available in `cf-deployment` v12.1.0 and later.

Passing values from `aws ecr get-login` into `cf push` will only work for about 12 hours, I'm told.

**Comment by tminussi** [comment]
That's correct, @pspinrad. But when running `cf push` with `aws ecr get-login` credentials _also_ works, so it may be wise to list both methods. What do you think?

Furthermore, thanks for adding that note to the docs.

**Comment by pspinrad** [comment]
@tminussi my understanding is that, yes, it'll work at first, but after the next ECR tokens refresh, in 12 hours or so, it won't work anymore-- and if so, we don't want to document something that'll get people in trouble like that.

**Comment by tminussi** [comment]
Re-authenticating is kind of a common pattern, so I think people would be OK with it as long as it's noted in the docs. 
While providing AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY is a good start, it does not cover all corner cases. If a user uses MFA, then AWS_SESSION_TOKEN is also necessary along with _temporary_ credentials, so re-authenticating every X amount of hours is a must for MFA users. 
Mentioning both authentication methods, in my opinion, covers the area that  AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY alone can't reach.
Of course, a third option would be to enable users to feed AWS_SECRET_ACCESS_KEY to the _cf push_ command, but I understand this may take some time.

Anyways, I was not able to authenticate the way it was documented, thus I opened this issue. I was only able to authenticate using the credentials returned by the `aws ecr get-login` command, even though it was never mentioned in the docs.

**Comment by tminussi** [comment]
@pspinrad Re-authenticating is kind of a common pattern, so I think people would be OK with it as long as it's noted in the docs.
While providing AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY is a good start, it does not cover all corner cases. If a user uses MFA, then AWS_SESSION_TOKEN is also necessary along with _temporary_ credentials, so re-authenticating every X amount of hours is a must for MFA users.
Mentioning both authentication methods, in my opinion, covers the area that AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY alone can't reach.
Of course, a third option would be to enable users to feed AWS_SECRET_ACCESS_KEY to the `cf push` command, but I understand this may take some time.

Anyways, I was not able to authenticate the way it was documented, thus I opened this issue. I was only able to authenticate using the credentials returned by the `aws ecr get-login` command, even though it was never mentioned in the docs.
