### ISSUE TITLE
Incorrect CLI usage info for binding a service instance

### ISSUE THREAD

**Issue by bwasmith** [cloudfoundry/docs-dev-guide#381]
Hello there!

### Arbitrary Parameters when Binding with an App Manifest
I believe the text on [this docs page](https://docs.pivotal.io/platform/application-service/2-7/devguide/services/application-binding.html#arbitrary-params-binding) needs to be updated:
```
As of cf CLI v6.12.1, Arbitrary Parameters are not supported in app manifests.
```

This is no longer true. Support for arbitrary parameters in an app manifest were introduced in `capi-release 1.80.0`. This is the relevant issue: https://github.com/cloudfoundry/cloud_controller_ng/issues/1332.

The app manifest specification in CAPI Docs has an example of a service declaration with parameters: http://v3-apidocs.cloudfoundry.org/version/release-candidate/#the-app-manifest-specification.

As for when this was specifically introduced, I could probably help provide that information. Maybe it is not necessary?

### Arbitrary Parameters in General

Additionally, I think that this section can also be removed: 
```
Arbitrary parameters require Cloud Foundry Command Line Interface (cf CLI) v6.12.1 or later.
```

This is the commit that introduced this: https://github.com/cloudfoundry/cli/commit/a95a44bee7d32b73748f668c9353b22d008a9a90

This was introduced in 2015, first included in tag `v6.12.0`. I think this is probably no longer relevant to PCF 2.7 customers, but I do not know for certain. 

### Slack Thread 
There was a PA who reached out to the cf-cli Pivotal Slack channel. Their customer was having trouble with this service document. 

https://pivotal.slack.com/archives/C0555EXQJ/p1572536010000300
_______

Please let me know if there is anything else I can help with! I was not sure how to reword the doc to include arbitrary parameters so I did not open a PR. 

Best,
Brendan and the CF CLI team

**Comment by mjgutermuth** [comment]
Hi there, apologies for the very late response! We did make this update [here](https://docs.pivotal.io/application-service/2-7/devguide/services/application-binding.html#arbitrary-params-binding). Thanks!
