### ISSUE TITLE
Consider the ability of using alias when sharing a service

### ISSUE THREAD

**Issue by Gustafioh** [cloudfoundry/docs-dev-guide#385]
I'm creating a new space to centralize the backups od DB and ELK Services across the ORG. I started with DB Services which have the same name in diferent spaces. Because I cannot give them an Alias, the Backup tool can only access one of the two services.

**Comment by mlimonczenko** [comment]
Hello @Gustafioh,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
