### ISSUE TITLE
Dev guide doesn't contain information on how to setup local cf dev environment

### ISSUE THREAD

**Issue by preetnitkkr** [cloudfoundry/docs-dev-guide#388]
The guide is very well written except one thing- it doesn't contain information how to create local debug environment as remote debugging by opening ssh tunnel is too slow and most of the time is not practical for real use cases.

**Comment by seviet** [comment]
Hi @preetnitkkr! 

Thank you so much for reaching out. Hopefully I am interpreting your feedback correctly, but you can create a local CF env with the CF Dev project. See https://github.com/cloudfoundry-incubator/cfdev 

If this does not address your comment, then feel free to reopen this issue.

I'll add some links to the CF Dev project in the docs.
