### ISSUE TITLE
Wrong manifest property name

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry/docs-dev-guide#391]
https://docs.cloudfoundry.org/devguide/deploy-apps/large-app-deploy.html mentions:
> set in the cc.packages.max\_package\_size property in the manifest

However the property is called `cc.packages.max_package_size` as in: 
https://github.com/cloudfoundry/capi-release/blob/d9d4eb522e400b7567effd8bb1fa89805add587f/jobs/cloud_controller_ng/spec#L544-L545

I think the problem is caused by escaping somewhere along the way until it reaches https://github.com/cloudfoundry/docs-dev-guide/blob/5020277d8a167e176f53a63857a930b86e307a3a/deploy-apps/large-app-deploy.html.md.erb#L15

**Comment by jncd** [comment]
Hi @hsiliev 
Thanks so much for logging this issue. 
I think it's fixed now. Let me know if you see problems.
Best regards, Jane
