### ISSUE TITLE
Consider to improve documentation around differences between shared and private domain

### ISSUE THREAD

**Issue by RageZBla** [cloudfoundry/docs-dev-guide#398]
The documentation has the following note but sadly it is under "Create an HTTP Route with a Path", I think it could helpful to user to copy the note under private and shared domains sections of the page (https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html).

> Note: Routes with the same domain and hostname but different paths can only be created in the same space. Private domains do not have this limitation.

**Comment by jncd** [comment]
Hi @RageZBla Thanks for logging this issue. We've added this information about the difference between shared and private domains to the docs. The attached screenshots highlight the new text.

![Screen Shot 2020-04-16 at 5 23 42 PM](https://user-images.githubusercontent.com/16601462/79593766-cd865400-8090-11ea-8e60-07b58e197600.png)

![Screen Shot 2020-04-17 at 8 55 55 AM](https://user-images.githubusercontent.com/16601462/79593741-c5c6af80-8090-11ea-938a-ac6aebe153dc.png)

**Comment by RageZBla** [comment]
@jncd thank you
