### ISSUE TITLE
Update documentation to include missing verb in warning

### ISSUE THREAD

**Issue by CambodianCoder** [cloudfoundry/docs-dev-guide#407]
Please consider adding a verb to the warning shown in the following screenshot. A verb such as "try" or "attempt" is sufficient.
This issue addresses line 495 of https://github.com/cloudfoundry/docs-dev-guide/blob/master/deploy-apps/manifest-attributes.html.md.erb

<img width="1641" alt="Screen Shot 2020-07-07 at 11 13 21 AM" src="https://user-images.githubusercontent.com/35553625/86817890-e163a580-c042-11ea-89e8-fe03d2acb187.png">

**Comment by animatedmax** [comment]
Hi @CambodianCoder This issue has been resolved by the following commit:
https://github.com/cloudfoundry/docs-dev-guide/commit/42ab5db6b3b49416b3b60cf015f4a52143ed53de
