### ISSUE TITLE
Incorrect text in Rolling-deploy page

### ISSUE THREAD

**Issue by stephanerenou** [cloudfoundry/docs-dev-guide#408]
On the limitations chapter the text says:
cf v3-ssh does not handle this scenario. You must use the cf v3-ssh command instead.
I guess it should say:
cf **ssh** does not handle this scenario. You must use the cf v3-ssh command instead.

Also in the prerequisites page you refer to deploy the cc_deployment_updater which points to https://github.com/cloudfoundry/cf-deployment/blob/master/operations/experimental/add-deployment-updater.yml which does not exists.

**Comment by cshollingsworth** [comment]
Hi, @stephanerenou ! Thanks for pointing this out. The text has now been corrected.
