### ISSUE TITLE
"Choosing the right plan" can be relocated

### ISSUE THREAD

**Issue by rmasand** [cloudfoundry/docs-dev-guide#42]
Hello,

On Services API, we were making some doc changes and noticed this section:

https://github.com/cloudfoundry/docs-dev-guide/blob/master/services/adding-a-service.html.md#-choosing-the-right-plan

We think this is correct and potentially valuable information, but may not apply to all users or plans. In particular, it's unlikely this would come into play when the user first chooses a service plan. It may be more relevant somewhere that refers to restarting CF or scaling app instances.

Let us know if you need more context as to why this might not belong in the services section.

/cc @mmb 

Thanks!

CF Services API

**Comment by jbheron** [comment]
As the services team consolidated information from this topic into docs-dev-guide/services/managing-services.html, I'm closing this issue. Let us know if there's any concern outstanding, given this update. Thanks!
