### ISSUE TITLE
Cannot access service

### ISSUE THREAD

**Issue by sundarvc** [cloudfoundry/docs-dev-guide#423]
Hi Team,

I have created a service instance and service-key in CF for a Spring Boot App. The Spring Boot App is deployed in k8s cluster and is available to CF through a broker. The deployment and registration with Service Broker in CF went fine and I am able to see the uri (https IP addr of Spring rest service) ,username and pwd in the generated service-key listing. However, when I use curl to call the REST endpoint I get "Operation Timeout Error" from curl. Looks like the ip addr does not work from my local machine. Can you tell me what is missing ?

Thanks,
Sundar

**Comment by mlimonczenko** [comment]
Hello @sundarvc,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
