### ISSUE TITLE
Add documentation to "Update Service Credentials" without downtime

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/docs-dev-guide#426]
Following the current documentation about [Update Service Credentials](https://docs.cloudfoundry.org/devguide/services/application-binding.html#update-credentials) applications require a downtime. Service credentials could be updated without a downtime in case a service broker generates new binding credentials for every new binding. Following steps could be used to updated the binding credentials without a downtime:

1. Start a blue-green update of the application as described [in](https://docs.cloudfoundry.org/devguide/deploy-apps/blue-green.html).
2. Execute "Step 2" in the above documentation with the `--no-start` parameter to prevent the application from starting right away.
3. After "Step 2" in the above documentation, create a new service binding for the desired service instance towards the newly deployed "Green" app. This will create a new set of binding credentials that are used by the "Green" app when it starts. Do the same for all other service bindings you might have.
4. `cf start` the "Green" application and continue with the rest of the documentation for blue-green updates.
5. At the end make sure to delete all service bindings to the "Blue" application which invalidates the corresponding binding credentials. For this you can use `cf delete` the "Blue" application or `cf stop` and `cf unbind`.

Do you think that this is a reasonable addition for the documentation?

**Comment by mlimonczenko** [comment]
Hello @beyhan,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.

**Comment by beyhan** [comment]
@mlimonczenko I have created https://github.com/cloudfoundry/docs-dev-guide/pull/429
