### ISSUE TITLE
Termination signal SIGTERM not captured by the javascript application on cf stop

### ISSUE THREAD

**Issue by mdnazgithub** [cloudfoundry/docs-dev-guide#427]
I have a CF node app running and I have some functions that need to be called as a part of cleanup on app exit. But unfortunately, I am not seeing the clean up happening as the application is not reacting to the SIGTERM event. The sample structure of the event listener is as follows,

process.on('SIGTERM', () => {
    console.log('SIGTERM signal received.');
    process.exit(0);
});

**Comment by pubtools-docs-helper** [comment]
Hi @mdnazgithub It looks like you're trying to troubleshoot a connection issue in CF. We recommend that you reach out for help in the https://cloudfoundry.slack.com -- perhaps either the #general or #cf-users channel. If you discover something that you believe requires a documentation update, please feel free to open up a new issue!
