### ISSUE TITLE
Outdated blue-green deployment example

### ISSUE THREAD

**Issue by calle2010** [cloudfoundry/docs-dev-guide#428]
When I try to follow the blue-green deployment example at 
https://docs.cloudfoundry.org/devguide/deploy-apps/blue-green.html
I fail with the command
`cf push Blue -n demo-time`
Error message is 

> Incorrect Usage: unknown flag `n'

**Comment by mlimonczenko** [comment]
Hello @calle2010,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
