### ISSUE TITLE
Is it better to specify no-route for sidekiq worker apps

### ISSUE THREAD

**Issue by wgu** [cloudfoundry/docs-dev-guide#43]
http://docs.cloudfoundry.org/buildpacks/ruby/ruby-tips.html#workers
http://docs.pivotal.io/pivotalcf/buildpacks/ruby/ruby-tips.html#workers

Users are asking if adding ``--no-route`` in CLI or ``no-route: true`` in manifest.yml to the worker app sounds better to them, as they should be background worker apps that serve no external requests. Please be advised. Thanks!

**Comment by animatedmax** [comment]
09 June 2015 - Added note on how to use `--no-routes` to the following topic:
http://cf-p1-docs-acceptance.cfapps.io/pivotalcf/buildpacks/ruby/ruby-tips.html#workers
https://www.pivotaltracker.com/story/show/95213664
