### ISSUE TITLE
Using Service Keys

### ISSUE THREAD

**Issue by MatKuhr** [cloudfoundry/docs-dev-guide#435]
Hi, I was wondering if it is possible to use service keys within applications to connect to services?

On [this documentation](https://docs.cloudfoundry.org/devguide/services/service-keys.html) I only found how to obtain them via CF cli. Is there a way the keys are provisioned to the application? Or are the service keys not intended to be used by applications?

**Comment by anita-flegg** [comment]
@gerg, @ameowlia - would you be able to answer this question?
Please let me know if I should just close it.

**Comment by anita-flegg** [comment]
No responses or activity - closing
