### ISSUE TITLE
Sidecar documentation

### ISSUE THREAD

**Issue by hananiel** [cloudfoundry/docs-dev-guide#438]
The instructions and samples mentioned [here](  https://github.com/cloudfoundry/docs-dev-guide/blob/master/sidecars.html.md.erb) raise the following questions for me:

Is it possible to employ sidecar app as ingress and egress proxy using this mechanism?
If so how? If not limitations should be documented. 
How does the [envoy release]( https://bosh.io/releases/github.com/cloudfoundry/envoy-release?all=1) accomplish this task?  Would probably make sense to compare the different ways sidecar technology is supported in CF.

**Comment by anita-flegg** [comment]
@hananiel , This issue is nearly 2 years old, so it may no longer be relevant. If these questions are still unanswered sufficiently in the docs, please bring it up in the CF slack channels. I'll be happy to update the documentation once all the information is available.
Thanks :)

**Comment by anita-flegg** [comment]
No response - closing
