### ISSUE TITLE
How to pass parameters to push and run Docker images in Cloud foundry cf push

### ISSUE THREAD

**Issue by viju2008** [cloudfoundry/docs-dev-guide#440]
Hi,

I went through the documentation. However i could not find how to pass to pass parameters to run Dockee image like -p or
-e.

Is it possible to use them along with CF PUSH ?

**Comment by viju2008** [comment]
Hello Any update on the same

**Comment by viju2008** [comment]
Hello any update on the same

**Comment by mjgutermuth** [comment]
Hi @viju2008,

This documentation repository is maintained by technical writers, not developers or support engineering.

For questions about the Cloud Foundry project, we recommend that you contact the cf-dev@lists.cloudfoundry.org mailing list or [Cloud Foundry Slack](https://cloudfoundry.slack.com/).
