### ISSUE TITLE
broken link in the docs

### ISSUE THREAD

**Issue by myminseok** [cloudfoundry/docs-dev-guide#457]
Hi, 
I've found the broken link on the documentation.
https://github.com/cloudfoundry/docs-dev-guide/blob/1ea8b99414f491ffca5b37fab435e2cfc0a67b99/deploy-apps/streaming-logs.html.md.erb#L236

the link should be 
from
```
https://github.com/cloudfoundry/loggregator-release/blob/develop/docs/java-multi-line-work-around.md
```
to
```
https://github.com/cloudfoundry/loggregator-release/blob/main/docs/java-multi-line-work-around.md
```

**Comment by anita-flegg** [comment]
Fixed in master and previous
