### ISSUE TITLE
Utilization of resources of a stopped application

### ISSUE THREAD

**Issue by sudarshang0007** [cloudfoundry/docs-dev-guide#461]
Can someone put some focus on stopping application.

The question is can we utilize the resources allocated to an application which is stopped?

e.g. application **sampleApp** is stopped, 2 Gb of memory is assigned to it. After stopping this application can we utilize the allocated memory to another application?
I dont want to delete this application.

**Comment by bobbygeeze** [comment]
Hi @sudarshang0007 can you provide doc references that relate to this issue?  Thanks

**Comment by anita-flegg** [comment]
No response. Closing.
