### ISSUE TITLE
Mention the CF version since which the readiness health checks are available

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/docs-dev-guide#488]
cf-deployment [v32.2.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v32.2.0) brings the `readiness health checks` which where documented with https://github.com/cloudfoundry/docs-dev-guide/pull/486. I was wondering whether we should mention some CF version since which the `readiness health checks` feature is available. Looking into the docs we don't seem to have mentioning of CF versioning but rather CLI Version or CF API versions. If we decide to mention a version maybe we could use the cf-deployment version for that. WDYT?

**Comment by anita-flegg** [comment]
@beyhan, sounds like a good idea. Where can we find this information?

**Comment by anita-flegg** [comment]
Thanks, @ameowlia. I added this info to the release notes and the healthchecks file.

**Comment by beyhan** [comment]
thank you @anita-flegg and @ameowlia!
