### ISSUE TITLE
Markdown rendering errors for routes-domains.html

### ISSUE THREAD

**Issue by Gerg** [cloudfoundry/docs-dev-guide#507]
![Screenshot 2024-05-21 at 4 31 56 PM](https://github.com/cloudfoundry/docs-dev-guide/assets/875892/32d078aa-0284-4665-b2e7-91702e52f33e)

https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#:~:text=o%20other%2Dorg-,%23%23%23%20Delete%20a%20route,-Developers%20can%20delete

**Comment by pspinrad** [comment]
Fixed-- thanks for pointing out!
