### ISSUE TITLE
mention cf CLI exit codes

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/docs-dev-guide#58]
We should mention that the cf CLI uses exit codes, useful for scripting: '0' means command was successful, any other value means it failed.
A new section in "Consistent Behavior to Help You Work Efficiently" in installcf/whats-new-v6.html.md.erb may be a good location.
We could include the commands used to check the exit code on each supported platform (Linux/Mac, Windows Command Line, Windows Powershell), as done here http://docs.aws.amazon.com/cli/latest/topic/return-codes.html.

**Comment by abbyachau** [comment]
Hi @dkoper, many thanks for confirming we can close this issue since it is covered in the larger rewrite of the cf CLI docs (see: https://github.com/cloudfoundry/docs-dev-guide/issues/58). 

Best,

Abby
