### ISSUE TITLE
remove references to version of cf CLI, migration

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/docs-dev-guide#59]
Many of the cf CLI sections are written towards users migrating from CLI v5 to v6.
v6 has been out for nearly two years now.
We should rewrite the docs to remove focus on migration:

* Make `Uninstall cf CLI v5` section less prominent (http://docs.cloudfoundry.org/devguide/installcf/install-go-cli.html#uninstall-gem)
* Remove version numbers in "For more information about cf CLI version 6, see Getting Started with cf CLI v6.", etc. (http://docs.cloudfoundry.org/devguide/installcf/install-go-cli.html#next-steps, etc.)
* Remove 6 "key differences" listed under `Getting Started with the cf CLI` (the note about Cloud Foundry administrators should be moved to a more appropriate location)  (http://docs.cloudfoundry.org/devguide/installcf/whats-new-v6.html)
* Remove `Installation` (already covered in `Installing the cf Command Line Interface`) (http://docs.cloudfoundry.org/devguide/installcf/whats-new-v6.html#install)

**Comment by abbyachau** [comment]
Thanks, Dies! This issue was resolved some time ago. Just noticed the Github issue was still open, so closing it out now. 

Abby
