### ISSUE TITLE
Lost details from cf-docs including multiple instance to cope with DEA evacuation process

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/docs-dev-guide#6]
Seems https://github.com/cloudfoundry/cf-docs/blob/a8d0d78fc1fd0b8b762b4ddab6165189566a680a/source/docs/using/deploying-apps/index.html.md#run-multiple-instances-to-increase-availability was lost while moving to docs-dev-guide

**Comment by animatedmax** [comment]
31 March 2014 - Documentation updated - https://www.pivotaltracker.com/story/show/67110120
