### ISSUE TITLE
Manifest page does not provide reset values in case of completely messing it up

### ISSUE THREAD

**Issue by lyanco** [cloudfoundry/docs-dev-guide#71]
Referencing https://github.com/cloudfoundry/docs-dev-guide/blob/40e97c92c24f0e3cb883573a7e0c4370e2cfbcf2/deploy-apps/manifest.html.md.erb#L114

I ran into an issue where I messed up my cf manifest by specifying a bunk value for "command". When I deleted it and it didn't change anything upon app push, I learned that previous manifest pushes take precedence over blank lines. I eventually figured out how to run my command, but for a bit I was completely lost as to how to turn back my command entry to its default and undo my mistake.

Can we provide instructions for "reseting" manifests? If it depends on language or framework, can we provide specific instructions?

Thanks!

Lee

**Comment by ljarzynski** [comment]
Hi @lyanco! Thanks for opening this issue. We modified the Deploying with Application Manifests topic to make it clear that explicitly setting the start command to null uses the default buildpack start command and overrides any previously specified value (generally resetting manifests is not possible from what we learned).  https://github.com/cloudfoundry/docs-dev-guide/blob/master/deploy-apps/manifest.html.md.erb#L137.
