### ISSUE TITLE
VCAP_APPLICATION env var is missing "uris" key in table

### ISSUE THREAD

**Issue by ryanmoran** [cloudfoundry/docs-dev-guide#8]
If you look at the table at https://github.com/cloudfoundry/docs-dev-guide/blob/master/deploy-apps/environment-variable.html.md#vcap_application, there is a table of keys and their description for the JSON contained in the VCAP_APPLICATION env var. There is also an example JSON output below the table. The example includes a "uris" key while the table does not.

It looks to me like the "uris" key is identical to "applications_uris", but I don't know for sure. I think this should probably be fixed in the docs, either by removing the "uris" key from the example, or adding the "uris" key as a item in the table.

FWIW, when I looked at the env vars for a running application, I do see the "uris" key.

**Comment by animatedmax** [comment]
Hi ryanmoran ,
You are correct, `uris` is an alias for `application_uris`. We've updated the topic to explicitly state this. 

Thank you!
