### ISSUE TITLE
Service keys description requires more explanation

### ISSUE THREAD

**Issue by glyn** [cloudfoundry/docs-dev-guide#80]
"Services Overview" gives only a [basic definition of service key](https://docs.cloudfoundry.org/devguide/services/#service-keys) and the link to [Managing Service Keys](https://docs.cloudfoundry.org/devguide/services/service-keys.html) sheds no further light on how service keys operate.

For instance, what use is made of a service key, or the name of a service key, once it has been created? How does a service key relate to an application-service instance binding? Will a binding include the credentials from a service key or is it up to the application developer to provide these credentials to the application by some other means.

**Comment by ljarzynski** [comment]
@glyn, thank you for opening this issue. Based on your feedback, we updated the Services Overview topic to clarify the difference between using Service Keys and using Application Binding (https://github.com/cloudfoundry/docs-dev-guide/blob/master/services/index.html.md.erb#L22). For the Managing Services Keys topic, we added example use cases to the intro (https://github.com/cloudfoundry/docs-dev-guide/blob/master/services/service-keys.html.md.erb#L10).
